application: comprices
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /load_country
  script: country_loader.py
  login: admin

- url: /load_state
  script: state_loader.py
  login: admin

- url: /load_city
  script: city_loader.py
  login: admin

- url: /.*
  script: index.py
